"use client";
import Link from "next/link";
import { useState } from "react";
import { cases, type CaseStudy } from "../data/site";
import { PageHero, PageShell } from "./SiteShell";

function CaseVisual({accent}:{accent:string}){return <div className="case-visual full" style={{"--case-accent":accent} as React.CSSProperties}><div className="case-map"><i className="heat h1"/><i className="heat h2"/><i className="heat h3"/>{[1,2,3,4,5].map(n=><b className={`point p${n}`} key={n}/>)}</div><div className="case-scale"><span>−30</span><i/><span>+30 mm/yr</span></div></div>}

export function ShowcasePage(){const [active,setActive]=useState(cases[0]);return <PageShell><PageHero eyebrow="CASE DECK · APPLICATIONS" title="典型 InSAR 应用案例" description="以卫星视角持续观察城市与关键基础设施，让隐蔽、缓慢的地表变化成为可追踪的风险线索。"/><section className="section case-deck showcase-section"><div className="case-tabs">{cases.map(item=><button className={active.key===item.key?"active":""} onClick={()=>setActive(item)} key={item.key}>{item.label}</button>)}</div><article className="case-feature"><div><span className="eyebrow">{active.kicker}</span><h2>{active.title}</h2><p>{active.description}</p><div className="tag-list">{active.tags.map(t=><span key={t}>{t}</span>)}</div><Link className="button primary" href={`/showcase/${active.key}`}>查看完整案例 <span>↗</span></Link></div><div><CaseVisual accent={active.accent}/><div className="case-metrics">{active.metrics.map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div></div></article><div className="case-list">{cases.map((item,index)=><Link href={`/showcase/${item.key}`} key={item.key}><span>0{index+1}</span><div><small>{item.kicker}</small><h3>{item.title}</h3><p>{item.description}</p></div><b>↗</b></Link>)}</div></section></PageShell>}

export function CaseDetailPage({item}:{item:CaseStudy}){return <PageShell><PageHero eyebrow={item.kicker} title={item.title} description={item.description}/><section className="section detail-story"><div className="story-intro"><div><span className="eyebrow">PROJECT BRIEF</span><h2>用连续时序补足传统巡查的空间盲区</h2></div><p>通过多时相 SAR 影像反演地表形变，形成从区域普查、异常识别到单点趋势核查的完整链路。案例数据为界面演示，后续可由真实项目接口原位替换。</p></div><div className="case-metrics large">{item.metrics.map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div><CaseVisual accent={item.accent}/><div className="detail-grid"><article><span>01</span><h3>空间筛查</h3><p>按速度、累计形变量与相干性组织监测点，识别持续异常的空间聚集特征。</p></article><article><span>02</span><h3>时间序列</h3><p>点击地图点位查看完整观测期曲线、趋势线和形变模式，支持异常点核查。</p></article><article><span>03</span><h3>成果交付</h3><p>将地图、曲线、统计和案例说明组合为适合汇报与工程沟通的 WebGIS 成果。</p></article></div><div className="story-action"><h2>在交互地图中查看点位分析</h2><Link className="button primary" href="/map">进入形变地图 ↗</Link></div></section></PageShell>}
