import Link from "next/link";
import { PageHero, PageShell } from "./SiteShell";

const contents={
 statistics:{eyebrow:"SPATIAL STATISTICS",title:"区域形变统计",description:"从单点观测上升到区域认知，比较速度分布、异常比例和重点区域。"},
 solutions:{eyebrow:"INSAR SOLUTIONS",title:"从数据处理到 WebGIS 交付",description:"以标准化产品链连接时序反演、质量控制、模式识别和在线发布。"},
 platform:{eyebrow:"PLATFORM ARCHITECTURE",title:"为大规模 InSAR 数据设计",description:"面对几十万点和数百期属性，采用分层存储、空间索引与按需加载，保持地图交互流畅。"},
 about:{eyebrow:"ABOUT THE PROJECT",title:"一个面向科研展示的 InSAR WebGIS",description:"LANJIFYW 将遥感处理、GIS 分析、数据工程与前端表达组合为可持续迭代的个人项目。"},
};
export function ContentPage({type}:{type:keyof typeof contents}){const c=contents[type];const cards= type==="statistics"?[["−1.7 mm/yr","区域平均速率"],["3.8%","异常点占比"],["12","重点监测区"],["1,264 km²","覆盖面积"]]:type==="solutions"?[["数据准备","SAR、轨道与 DEM"],["时序反演","速度与累计形变"],["质量控制","相干性与异常值"],["成果发布","地图、曲线和接口"]]:type==="platform"?[["对象存储","原始 CSV / Parquet"],["空间数据库","PostGIS 与索引"],["地图服务","矢量瓦片 / COG"],["前端查询","视域与点位按需加载"]]:[["遥感处理","InSAR 数据产品"],["GIS 分析","空间统计与制图"],["数据工程","大文件与接口设计"],["前端表达","React WebGIS"]];return <PageShell><PageHero {...c}/><section className="section"><div className="info-grid">{cards.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h2>{a}</h2><p>{b}</p></article>)}</div>{type==="statistics"&&<><div className="statistics-layout"><article><span className="eyebrow">VELOCITY DISTRIBUTION</span><h2>速度频数分布</h2><div className="histogram-modern">{[12,18,30,48,72,94,82,58,39,25,13,7].map((v,i)=><i style={{height:`${v}%`}} key={i}/>)}</div><div className="hist-axis"><span>−30</span><span>−15</span><span>0</span><span>+15</span><span>+30 mm/yr</span></div></article><article><span className="eyebrow">FOCUS AREAS</span><h2>重点区域</h2>{[["美兰区","−5.8",82],["秀英区","−4.3",66],["龙华区","−3.6",54],["琼山区","+2.1",39]].map(([n,v,w])=><div className="rank-row" key={String(n)}><span>{n}</span><i><b style={{width:`${w}%`}}/></i><strong>{v}</strong></div>)}</article></div></>}{type==="platform"&&<div className="architecture-flow"><span>2GB CSV</span><i>→</i><span>分片上传</span><i>→</i><span>Parquet / PostGIS</span><i>→</i><span>矢量瓦片</span><i>→</i><span>WebGIS</span></div>}<div className="story-action"><h2>{type==="about"?"继续了解项目能力":"进入平台体验完整交互"}</h2><Link className="button primary" href={type==="about"?"/showcase":"/map"}>{type==="about"?"浏览案例":"打开地图"} ↗</Link></div></section></PageShell>}
