"use client";
import "leaflet/dist/leaflet.css";
import { useEffect, useMemo, useRef, useState } from "react";
import type { InsarPoint } from "../data/site";
import { colorForMode, deformationModeOrder, normalizedMode, type AnalysisMapView } from "../lib/analysis-context";
import { colorFor, renderValue, type RenderStyle } from "../lib/insar";

type Visible={points:boolean;boundary:boolean;risk:boolean;quality:boolean};
type SelectionMode="single"|"compare"|"compareBox"|"box";
type Props={points:InsarPoint[];selected:InsarPoint|null;onSelect:(p:InsarPoint)=>void;onBoxSelect:(p:InsarPoint[],bounds:[number,number,number,number])=>void;onViewChange:(view:AnalysisMapView)=>void;visible:Visible;base:string;tdtKey:string;customBasemap:string;baseOpacity:number;coherenceThreshold:number;layoutToken:string;renderStyle:RenderStyle;compareIds:string[];boxIds:string[];selectionMode:SelectionMode;highlightKind:"region"|"filter"|"anomaly";showSelectionRectangle:boolean;selectionBounds:[number,number,number,number]|null;initialView:AnalysisMapView|null};
const tdtUrl=(layer:string,key:string)=>`https://t{s}.tianditu.gov.cn/${layer}_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=${layer}&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILECOL={x}&TILEROW={y}&TILEMATRIX={z}&tk=${encodeURIComponent(key)}`;
const attributeLabel=(style:RenderStyle)=>style.attribute==="velocity"?"年均形变速率":style.attribute==="displacement"?"当前期累计形变量":style.attribute==="stageVelocity"?"时间区间阶段速率":style.attribute==="mode"?"形变模式":style.attribute==="coherence"?"相干性":"缺测率";

export default function WebGisMap({points,selected,onSelect,onBoxSelect,onViewChange,visible,base,tdtKey,customBasemap,baseOpacity,coherenceThreshold,layoutToken,renderStyle,compareIds,boxIds,selectionMode,highlightKind,showSelectionRectangle,selectionBounds,initialView}:Props){
  const host=useRef<HTMLDivElement>(null),map=useRef<any>(null),Lref=useRef<any>(null),baseLayers=useRef<any[]>([]),pointLayer=useRef<any>(null),riskLayer=useRef<any>(null),qualityLayer=useRef<any>(null),selectionLayer=useRef<any>(null),boundary=useRef<any>(null),lastPoints=useRef<InsarPoint[]|null>(null),boxRect=useRef<any>(null),savedBoxRect=useRef<any>(null),cursorFrame=useRef(0),initialViewApplied=useRef(false),callbacks=useRef({points,onBoxSelect,onSelect,onViewChange,selectionMode});const [cursor,setCursor]=useState("移动鼠标查看经纬度"),[ready,setReady]=useState(false);
  const pointById=useMemo(()=>new Map(points.map(p=>[p.id,p])),[points]);
  const presentModes=useMemo(()=>{const found=new Set(points.map(point=>normalizedMode(point.mode)));return deformationModeOrder.filter(mode=>found.has(mode))},[points]);
  callbacks.current={points,onBoxSelect,onSelect,onViewChange,selectionMode};
  useEffect(()=>{let dead=false;import("leaflet").then(mod=>{if(dead||!host.current)return;const L=mod.default;Lref.current=L;const m=L.map(host.current,{center:[20.04,110.33],zoom:12,zoomControl:false,preferCanvas:true,boxZoom:false});map.current=m;L.control.zoom({position:"bottomright"}).addTo(m);const emitView=()=>{const center=m.getCenter(),bounds=m.getBounds();callbacks.current.onViewChange({center:[center.lat,center.lng],zoom:m.getZoom(),bounds:[bounds.getWest(),bounds.getSouth(),bounds.getEast(),bounds.getNorth()]})};m.on("moveend",emitView);m.on("zoomend",emitView);m.on("mousemove",(e:any)=>{if(cursorFrame.current)return;cursorFrame.current=window.requestAnimationFrame(()=>{cursorFrame.current=0;setCursor(`${e.latlng.lng.toFixed(6)}° E · ${e.latlng.lat.toFixed(6)}° N`)})});m.on("mouseout",()=>setCursor("移动鼠标查看经纬度"));m.on("click",(e:any)=>{if(callbacks.current.selectionMode==="box"||callbacks.current.selectionMode==="compareBox")return;const click=m.latLngToContainerPoint(e.latlng);let nearest:InsarPoint|undefined,distance=18;callbacks.current.points.forEach(point=>{const pixel=m.latLngToContainerPoint([point.lat,point.lon]),next=click.distanceTo(pixel);if(next<=distance){distance=next;nearest=point}});if(nearest)callbacks.current.onSelect(nearest)});emitView();setReady(true)});return()=>{dead=true;if(cursorFrame.current)window.cancelAnimationFrame(cursorFrame.current);map.current?.remove();map.current=null}},[]);
  useEffect(()=>{const L=Lref.current,m=map.current;if(!L||!m)return;baseLayers.current.forEach(layer=>m.removeLayer(layer));baseLayers.current=[];const add=(url:string,options:any)=>{const layer=L.tileLayer(url,{crossOrigin:true,opacity:baseOpacity,...options}).addTo(m);baseLayers.current.push(layer)};if(base==="custom"&&customBasemap) add(customBasemap,{attribution:"Custom XYZ / WMTS",maxZoom:20});else if(base==="esri")add("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"Tiles © Esri",maxZoom:18});else if(base==="gray")add("https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}",{attribution:"Tiles © Esri",maxZoom:16});else if(base.startsWith("tdt")&&tdtKey){const imagery=base==="tdt_img";add(tdtUrl(imagery?"img":"vec",tdtKey),{subdomains:"01234567",attribution:"© 天地图",maxZoom:18});add(tdtUrl(imagery?"cia":"cva",tdtKey),{subdomains:"01234567",attribution:"© 天地图注记",maxZoom:18})}else add("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{subdomains:"abc",attribution:"© OpenStreetMap contributors",maxZoom:19})},[base,tdtKey,customBasemap,baseOpacity,ready]);
  useEffect(()=>{const L=Lref.current,m=map.current;if(!L||!m||!points.length)return;[pointLayer,riskLayer,qualityLayer,boundary].forEach(r=>{if(r.current)m.removeLayer(r.current)});const pointRenderer=L.canvas({padding:.5,tolerance:12}),riskRenderer=L.canvas({padding:.5,tolerance:15}),qualityRenderer=L.canvas({padding:.5,tolerance:12});pointLayer.current=L.layerGroup();riskLayer.current=L.layerGroup();qualityLayer.current=L.layerGroup();const bounds=L.latLngBounds(points.map(p=>[p.lat,p.lon]));boundary.current=L.rectangle(bounds.pad(.04),{color:"#1677ff",weight:1.5,dashArray:"6 5",fill:false,interactive:false});points.forEach(p=>{const value=renderStyle.attribute==="mode"?0:renderValue(p,renderStyle),color=renderStyle.attribute==="mode"?colorForMode(p.mode):colorFor(value,renderStyle),risk=Math.abs(p.velocity)>=3,quality=(p.coherence>0&&p.coherence<coherenceThreshold)||p.missingRate>.2;const baseStyle={renderer:pointRenderer,radius:6.5,color:"rgba(255,255,255,.92)",weight:1.5,fillColor:color,fillOpacity:.92};const marker=L.circleMarker([p.lat,p.lon],baseStyle);const shown=renderStyle.attribute==="mode"?normalizedMode(p.mode):`${value.toFixed(2)} ${renderStyle.attribute==="coherence"?"":renderStyle.attribute==="missing"?"%":renderStyle.attribute==="displacement"?"mm":"mm/yr"}`;const focus=()=>{marker.setStyle({radius:9,weight:2.6,color:"#071a38",fillOpacity:1});marker.bringToFront()},blur=()=>marker.setStyle(baseStyle),proxy=(overlay:any)=>overlay.on("mouseover",focus).on("mouseout",blur);marker.bindTooltip(`<b>${p.id}</b><br>${normalizedMode(p.mode)}<br>${shown}`);marker.on("mouseover",focus);marker.on("mouseout",blur);marker.addTo(pointLayer.current);if(risk)proxy(L.circleMarker([p.lat,p.lon],{renderer:riskRenderer,radius:12,color:"#e94b4b",weight:1.5,fillColor:"#e94b4b",fillOpacity:.1,interactive:true,bubblingMouseEvents:true})).addTo(riskLayer.current);if(quality)proxy(L.circleMarker([p.lat,p.lon],{renderer:qualityRenderer,radius:10,color:"#ffba08",weight:2,dashArray:"3 2",fill:false,interactive:true,bubblingMouseEvents:true})).addTo(qualityLayer.current)});if(visible.points)pointLayer.current.addTo(m);if(visible.risk)riskLayer.current.addTo(m);if(visible.quality)qualityLayer.current.addTo(m);if(visible.boundary)boundary.current.addTo(m);if(lastPoints.current!==points){if(initialView)m.setView(initialView.center,initialView.zoom,{animate:false});else m.fitBounds(bounds.pad(.16),{maxZoom:14,animate:true});lastPoints.current=points}},[points,visible.points,visible.risk,visible.quality,visible.boundary,renderStyle,coherenceThreshold,ready]);
  useEffect(()=>{const m=map.current;if(!ready||!m||!initialView||initialViewApplied.current)return;initialViewApplied.current=true;m.setView(initialView.center,initialView.zoom,{animate:false})},[initialView,ready]);
  useEffect(()=>{const L=Lref.current,m=map.current;if(!L||!m)return;if(selectionLayer.current)m.removeLayer(selectionLayer.current);selectionLayer.current=L.layerGroup();const renderer=L.canvas({padding:.5}),boxed=new Set(boxIds),compared=new Set(compareIds),boxColor=highlightKind==="anomaly"?"#d62f2f":highlightKind==="filter"?"#0756c9":"#7a4a00",boxFill=highlightKind==="anomaly"?"#ff4d4f":highlightKind==="filter"?"#58a6ff":"#ffd22e";const addHighlight=(p:InsarPoint,kind:"box"|"compare"|"selected")=>L.circleMarker([p.lat,p.lon],{renderer,radius:kind==="selected"?9:kind==="compare"?8:highlightKind==="anomaly"?8:7,color:kind==="box"?boxColor:"#071a38",weight:kind==="box"?highlightKind==="anomaly"?2.2:1.5:2.5,fillColor:kind==="box"?boxFill:kind==="compare"?"#fff36d":"#ffd22e",fillOpacity:kind==="box"?highlightKind==="anomaly"?.96:1:.94,interactive:false}).addTo(selectionLayer.current);boxIds.forEach(id=>{const p=pointById.get(id);if(p)addHighlight(p,"box")});compareIds.forEach(id=>{const p=pointById.get(id);if(p&&!boxed.has(id))addHighlight(p,"compare")});if(selected&&!boxed.has(selected.id)&&!compared.has(selected.id))addHighlight(selected,"selected");if(visible.points)selectionLayer.current.addTo(m);return()=>{if(selectionLayer.current)m.removeLayer(selectionLayer.current)}},[selected,compareIds,boxIds,pointById,visible.points,ready,highlightKind]);
  useEffect(()=>{const L=Lref.current,m=map.current;if(!L||!m)return;let start:any=null,startPoint:any=null;const canDraw=()=>selectionMode==="box"||selectionMode==="compareBox";const down=(e:any)=>{if(!canDraw()||e.originalEvent?.button)return;start=e.latlng;startPoint=m.latLngToContainerPoint(e.latlng);m.dragging.disable();if(boxRect.current)m.removeLayer(boxRect.current);boxRect.current=L.rectangle(L.latLngBounds(start,start),{color:"#1677ff",weight:1.5,dashArray:"5 4",fillColor:"#1677ff",fillOpacity:.08,interactive:false}).addTo(m)};const move=(e:any)=>{if(start&&boxRect.current)boxRect.current.setBounds(L.latLngBounds(start,e.latlng))};const up=(e:any)=>{if(!start||!startPoint)return;const endPoint=m.latLngToContainerPoint(e.latlng),minX=Math.min(startPoint.x,endPoint.x),maxX=Math.max(startPoint.x,endPoint.x),minY=Math.min(startPoint.y,endPoint.y),maxY=Math.max(startPoint.y,endPoint.y),bounds=L.latLngBounds(start,e.latlng),chosen=callbacks.current.points.filter(p=>{const pt=m.latLngToContainerPoint([p.lat,p.lon]);return pt.x>=minX&&pt.x<=maxX&&pt.y>=minY&&pt.y<=maxY});callbacks.current.onBoxSelect(chosen,[bounds.getWest(),bounds.getSouth(),bounds.getEast(),bounds.getNorth()]);if(savedBoxRect.current)m.removeLayer(savedBoxRect.current);savedBoxRect.current=L.rectangle(bounds,{color:"#1677ff",weight:2,dashArray:"6 5",fillColor:"#1677ff",fillOpacity:.06,interactive:false}).addTo(m);if(boxRect.current)m.removeLayer(boxRect.current);boxRect.current=null;start=null;startPoint=null;m.dragging.enable()};m.on("mousedown",down);m.on("mousemove",move);m.on("mouseup",up);return()=>{m.off("mousedown",down);m.off("mousemove",move);m.off("mouseup",up);if(boxRect.current)m.removeLayer(boxRect.current);m.dragging.enable()}},[selectionMode]);
  useEffect(()=>{const L=Lref.current,m=map.current;if(!L||!m)return;if(savedBoxRect.current){m.removeLayer(savedBoxRect.current);savedBoxRect.current=null}if(showSelectionRectangle&&selectionBounds){const [west,south,east,north]=selectionBounds;savedBoxRect.current=L.rectangle([[south,west],[north,east]],{color:"#1677ff",weight:2,dashArray:"6 5",fillColor:"#1677ff",fillOpacity:.06,interactive:false}).addTo(m)}},[showSelectionRectangle,selectionBounds,ready]);
  useEffect(()=>{const timer=window.setTimeout(()=>map.current?.invalidateSize({pan:false}),220);return()=>window.clearTimeout(timer)},[layoutToken]);
  const unit=renderStyle.attribute==="displacement"?"mm":renderStyle.attribute==="coherence"?"":renderStyle.attribute==="missing"?"%":"mm/yr";
  return <section className={`gis-map selection-${selectionMode}`}><div ref={host} className="leaflet-host"/><div className={`map-badge ${renderStyle.attribute==="mode"?"mode-map-badge":""}`}><span>{attributeLabel(renderStyle)}</span>{renderStyle.attribute==="mode"?<div className="mode-map-legend">{presentModes.map(mode=><small key={mode}><i style={{background:colorForMode(mode)}}/>{mode}</small>)}</div>:<><i style={{background:`linear-gradient(90deg,${renderStyle.colors.join(",")})`}}/><small>{renderStyle.min}　间距 {renderStyle.interval}　{renderStyle.max} {unit}</small></>}</div><div className="map-coordinates"><b>{cursor}</b><span>EPSG:4326 · WGS84</span></div>{selectionMode==="box"&&<div className="box-hint">在地图上拖动矩形进行区域统计</div>}{selectionMode==="compareBox"&&<div className="box-hint">矩形框选仅用于区域统计，点选多点用于曲线对比</div>}</section>
}
